Repository mohitjaisal/GithubCardss, pull requests merged in 2021-10, with the labels that each got.

#2 add favicon
  .DS_Store
  favicon.png
  index.html
Labels: bug, enhancement, Hactoberfest, hactoberfest-accepted

#4 refactor, responsive
  script.js
  style.css
Labels: bug, enhancement, Hactoberfest, hactoberfest-accepted

#5 Readme enhancement
  GithubFetch-Demo.gif
  README.md
Labels: documentation, enhancement, Hactoberfest, hactoberfest-accepted

#18 Update README.md
  README.md
Labels: Hactoberfest, hactoberfest-accepted
